#pragma once

#include "event.h"
#include <string>

namespace quantcore {

    /**
     * What the strategy wants to do
     */
    enum class SignalType {
        BUY,
        SELL,
        HOLD
    };

    /**
     * Strategy decision
     *
     * Generated by strategy when it sees a trading opportunity.
     * This gets converted to OrderEvent by the portfolio manager.
     */
    class SignalEvent : public Event {
    public:
        SignalEvent(
            const std::string& symbol,
            int64_t timestamp_ns,
            SignalType signal_type,
            double strength = 1.0,
            const std::string& strategy_id = "default"
        )
            : Event(EventType::SIGNAL, timestamp_ns)
            , symbol_(symbol)
            , signal_type_(signal_type)
            , strength_(strength)
            , strategy_id_(strategy_id)
        {
        }

        std::string get_symbol() const { return symbol_; }
        SignalType get_signal_type() const { return signal_type_; }
        double get_strength() const { return strength_; }
        std::string get_strategy_id() const { return strategy_id_; }

        std::string to_string() const override {
            std::string signal_str;
            switch (signal_type_) {
                case SignalType::BUY: signal_str = "BUY"; break;
                case SignalType::SELL: signal_str = "SELL"; break;
                case SignalType::HOLD: signal_str = "HOLD"; break;
            }

            return "SignalEvent(symbol=" + symbol_ +
                   ", signal=" + signal_str +
                   ", strength=" + std::to_string(strength_) +
                   ", strategy=" + strategy_id_ + ")";
        }

    private:
        std::string symbol_;
        SignalType signal_type_;
        double strength_;      // Signal confidence (0.0 - 1.0)
        std::string strategy_id_;
    };

}